# Generated by Django 4.0.3 on 2022-04-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'liker')},
        ),
    ]
