# Generated by Django 4.0.3 on 2022-04-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
    ]
